# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# ----- adding some randon to kick build
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/aspnetcore-build

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export IMAGE_COMPLETE_NAME=tzatziki/minutz-api:3.2.39.$BITBUCKET_BUILD_NUMBER
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker build -t $IMAGE_COMPLETE_NAME .
          - docker push $IMAGE_COMPLETE_NAME