# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# ----- adding some randon to kick build
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/aspnetcore-build

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          # - export IMAGE_COMPLETE_NAME=$IMAGE_NAME:1.0.0.$BITBUCKET_BUILD_NUMBER
          # - dotnet restore src/minutz.sln
          # - dotnet build src/minutz.sln -c pipelines
          # - dotnet test src/Tests/Tests.csproj
          #- dotnet test src/TestIntegrations/TestIntegrations.csproj
          # - dotnet publish src/minutz.sln -c pipelines -o ../../dist
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker build -t $IMAGE_COMPLETE_NAME -f api.Dockerfile .
          - docker push $IMAGE_COMPLETE_NAME