version: '2'

services:
  minutz-api:
    image: minutz-api
    environment:
      - AUTH0CLIENTSECRET=3_ji0JgkrygjDWRkJtYGcrv5TN9eIsoZAbKi7bmkKiUqwpo3lOryhaMvOTlZRSDZ
      - AUTH0CLIENTID=spEQucIOEbSBvkixqRHzkKDHNYRaGy3J
      - AUTH0DOMAIN=tzatziki-minutz.auth0.com
      - AUTH0CALLBACKURL=http://localhost:60856/signin-auth0
    ports:
      - "5555:80"
    build:
      context: ./minutz-api
      dockerfile: Dockerfile
  mintz-db:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    volumes:
      - "./minutz-database/data:/var/opt/mssql/data"
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"