version: '3'

services:
  api:
    image: api
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DEFAULT_CATALOGUE=minutz-test
      - SERVER_ADDRESS=docker-durban.database.windows.net,1433
      - DEFAULT_SCHEMA=app
      - DEFAULT_USER=tzatziki
      - DEFAULT_PASSWORD=40Tep25hUXnz
      - AUTHORITY=https://dockerdurban.auth0.com/
