version: '3'

services:
  api:
    image: api
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DEFAULT_CATALOGUE=minutz
      - SERVER_ADDRESS=tcp:127.0.0.1,1433,
      - DEFAULT_SCHEMA=app
      - DEFAULT_USER=sa
      - DEFAULT_PASSWORD=SqlServer1234!
      - AUTHORITY=https://dockerdurban.auth0.com/
