version: '2'

services:
  minutz-api:
    image: minutz-api
    ports:
      - "5555:80"
    build:
      context: ./minutz-api
      dockerfile: Dockerfile
  mintz-db:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    volumes:
      - "./minutz-database/data:/var/opt/mssql/data"
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"