version: "3"

services:
  mssql:
      image: 'microsoft/mssql-server-linux'
      ports:
          - '1433:1433'
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=SqlServer1234!
      volumes:
          - app_docker_db:/var/lib/mssql/data
volumes:
  app_docker_db: