version: '3'

services:
  api:
    image: api
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=
      - DEFAULT_CATALOGUE=minutz
      - DEFAULT_SCHEMA=app
      - DEFAULT_USER=sa
      - DEFAULT_PASSWORD=SqlServer1234!
      - AUTHORITY=https://dockerdurban.auth0.com/
  data:
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlServer1234!
    volumes:
      - .\mssql:/var/opt/mssql