# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/aspnetcore-build:1.0-1.1

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE_NAME=tzatziki/minutz:$BITBUCKET_BUILD_NUMBER
          - export WEB_IMAGE_NAME=tzatziki/minutz-ui:$BITBUCKET_BUILD_NUMBER
          - dotnet restore src/minutz.sln
          - dotnet build src/minutz.sln -c pipelines
          - dotnet test src/minutz.tests.core/minutz.tests.core.csproj
          - dotnet publish src/minutz.sln -c pipelines -o ../../dist
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          ##- docker build -t $IMAGE_NAME -f .docker\apibuild\Dockerfile .
          # authenticate with the Docker Hub registry
          
          # push the new Docker image to the Docker registry
          ##- docker push $IMAGE_NAME
          - docker build -t $WEB_IMAGE_NAME -f ci.Dockerfile .
          - docker push $WEB_IMAGE_NAME
          ##- docker-compose -f docker-compose.production.yml build